# Generated by Django 5.1.3 on 2024-12-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pickup_location_name',
            field=models.CharField(default='Cornmarket Street', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
