# Generated by Django 5.1.3 on 2024-12-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0006_alter_product_image_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
