# Generated by Django 5.1.3 on 2024-12-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0009_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='dropoff_location',
            field=models.CharField(default='Balliol College', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='pickup_location',
            field=models.CharField(default='Cornmarket Street', max_length=100),
        ),
    ]
