# Generated by Django 5.1.3 on 2024-12-21 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0012_activedelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenDeliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_deliveries', to='backend1.product')),
            ],
        ),
    ]
