# Generated by Django 5.1.3 on 2024-12-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0013_opendeliveries'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='authentication_code',
            field=models.IntegerField(default=0),
        ),
    ]
