# Generated by Django 5.1.3 on 2024-12-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0014_product_authentication_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
