# Generated by Django 5.1.3 on 2024-12-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0015_delete_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
