# Generated by Django 5.1.3 on 2024-12-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0016_profile_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
