# Generated by Django 5.1.3 on 2024-12-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0017_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buyer_latitude',
            field=models.DecimalField(blank=True, decimal_places=20, default=None, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='buyer_longitude',
            field=models.DecimalField(blank=True, decimal_places=20, default=None, max_digits=100, null=True),
        ),
    ]
