# Generated by Django 5.1.3 on 2024-12-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0019_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delivering_status',
            field=models.BooleanField(default=False),
        ),
    ]
