# Generated by Django 5.1.3 on 2024-12-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0020_profile_delivering_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credit',
            field=models.FloatField(default=0),
        ),
    ]
