# Generated by Django 5.1.3 on 2024-12-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0022_product_deliverer'),
        ('backend1', '0022_product_pickup_latitude_product_pickup_longitude'),
    ]

    operations = [
    ]
